networks:
  app-net:
    driver: bridge

volumes:
  influxdb-data:

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    networks: [app-net]
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    networks: [app-net]
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  # SERVICIO NUEVO: Configura la infraestructura de Kafka
  kafka-setup:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-setup
    networks: [app-net]
    volumes:
      - ./infra/init-kafka.sh:/init-kafka.sh:z  # <-- FLAG :z PARA SELINUX
    entrypoint: ["/bin/bash", "/init-kafka.sh"]
    depends_on:
      kafka: 
        condition: service_healthy #evita que falle por no encontrar kafka.

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    networks: [app-net]
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminpassword
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUX_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUX_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUX_TOKEN}
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  producer:
    build: ./producer
    container_name: producer
    networks: [app-net]
    depends_on:
      kafka-setup:
        condition: service_completed_successfully # Espera a que el script infra termine.
    env_file: .env
    restart: on-failure

  consumer:
    build: ./consumer
    container_name: consumer
    networks: [app-net]
    depends_on:
      kafka-setup:
        condition: service_completed_successfully
      influxdb:
        condition: service_healthy
    env_file: .env
    restart: on-failure

  dashboard:
    build: ./dashboard
    container_name: dashboard
    networks: [app-net]
    ports:
      - "8050:8050"
    depends_on:
      influxdb:
        condition: service_healthy
    env_file: .env
    restart: on-failure